# Netlify configuration file

# Build settings
[build]
  # Directory to change to before starting a build
  base = "frontend/"
  
  # Directory that contains the deploy-ready HTML files
  publish = "dist/"
  
  # Default build command with improved reliability - install dev dependencies
  command = "npm ci --prefer-offline --include=dev && echo 'Dependencies installed successfully' && npm run build:netlify"
  
  # Ignore Python runtime files - frontend only needs Node.js
  ignore = "cd .. && test -f runtime.txt"

# Production context: all deploys from the main branch 
# will inherit these settings
[context.production.environment]
  NODE_ENV = "production"
  
# Redirects and headers
# Handle all routes under /sheetgpt/ for SPA
[[redirects]]
  from = "/sheetgpt/*"
  to = "/index.html"
  status = 200

# Handle the /sheetgpt base path
[[redirects]]
  from = "/sheetgpt"
  to = "/index.html"
  status = 200

# Default SPA handling for root path (assuming you'll have a separate homepage)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Browser caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"