# Netlify configuration file

# Build settings
[build]
  # Directory to change to before starting a build
  base = "frontend/"
  
  # Directory that contains the deploy-ready HTML files
  publish = "dist/"
  
  # Default build command
  command = "npm install && npm run build"

# Production context: all deploys from the main branch 
# will inherit these settings
[context.production.environment]
  NODE_ENV = "production"
  
# Redirects and headers
[[redirects]]
  # Redirect all routes to index.html (SPA setup)
  from = "/*"
  to = "/index.html"
  status = 200

# Browser caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"