# Root Netlify configuration file
# This overrides any Python configuration for the frontend deployment

[build]
  # Only deploy the frontend directory
  base = "frontend/"
  
  # Directory that contains the deploy-ready HTML files
  publish = "dist/"
  
  # Default build command
  command = "npm install && npm run build"

# Disable Python-related build steps entirely
[build.environment]
  NETLIFY_USE_PYTHON = "false"
  NETLIFY_USE_YARN = "true"
  NODE_VERSION = "16"

# Production context settings
[context.production.environment]
  NODE_ENV = "production"