version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./credentials:/app/credentials
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/sheetgpt
      - PYTHONPATH=/app
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sheetgpt
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 