services:
  # Development frontend service with HMR completely disabled
  frontend:
    # Override command - no need to rebuild image
    command: echo "Starting in no-HMR mode..." && npm run dev:nohmr