# Netlify configuration file for the root of the monorepo.

[build]
  # 1. The command to run to build your site. We build from the root
  #    but explicitly target the frontend workspace.
  command = "yarn workspace sheetgpt-frontend build"
  
  # 2. The directory to publish, relative to the repository root.
  publish = "frontend/dist"

[build.environment]
  # 3. Explicitly set the Node.js version to ensure consistency.
  NODE_VERSION = "18"
  
  # 4. Set NODE_ENV to "production" to ensure Vite builds correctly.
  NODE_ENV = "production" 

  # 5. Force Yarn to install devDependencies, which are needed for the build command.
  YARN_FLAGS = "--production=false"

# Redirect rule for the root domain.
# This sends visitors from 88gpts.com to the app's entry point.
[[redirects]]
  from = "/"
  to = "/sheetgpt"
  status = 302 # Temporary redirect

# Primary redirect rule for the Single Page Application (SPA).
# This rule is crucial: it serves your app's index.html for any path
# under /sheetgpt/, allowing React Router to handle the URL.
[[redirects]]
  from = "/sheetgpt/*"
  to = "/sheetgpt/index.html"
  status = 200 