# Netlify configuration file for the root of the monorepo.

[build]
  # 1. The command to run to build your site. We build from the root
  #    but explicitly target the frontend workspace.
  command = "yarn workspace sheetgpt-frontend build"
  
  # 2. The directory to publish, relative to the repository root.
  publish = "frontend/dist"

[build.environment]
  # 3. Explicitly set the Node.js and Yarn versions to ensure consistency.
  #    We are matching the Yarn version from the working Digital Ocean environment.
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"
  
  # 4. Set NODE_ENV to "development" to force installation of devDependencies
  #    which are required for the build command.
  NODE_ENV = "development" 