"""manual_add_division_conference

Revision ID: 47d196c4be3e
Revises: b667cd5de716
Create Date: 2025-03-13 00:42:56.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47d196c4be3e'
down_revision: Union[str, None] = 'b667cd5de716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('divisions_conferences',
    # sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    # sa.Column('league_id', postgresql.UUID(as_uuid=True), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('type', sa.String(length=50), nullable=False),
    # sa.Column('region', sa.String(length=100), nullable=True),
    # sa.Column('description', sa.Text(), nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    # sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('league_id', 'name', name='uq_division_conference_name_per_league')
    # )
    # op.create_index(op.f('ix_divisions_conferences_name'), 'divisions_conferences', ['name'], unique=False)
    pass # Made no-op as table is created by f626a8bff0f1
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_divisions_conferences_name'), table_name='divisions_conferences')
    # op.drop_table('divisions_conferences')
    pass # Made no-op
    # ### end Alembic commands ### 