"""add_league_nickname_field

Revision ID: dd64f60a5e18
Revises: c1b2744b8cdf
Create Date: 2025-03-13 18:35:11.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd64f60a5e18'
down_revision: Union[str, None] = 'c1b2744b8cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('leagues', sa.Column('nickname', sa.String(length=20), nullable=True))
    # op.create_index(op.f('ix_leagues_nickname'), 'leagues', ['nickname'], unique=False)
    # op.add_column('divisions_conferences', sa.Column('nickname', sa.String(length=20), nullable=True))
    # op.create_index(op.f('ix_divisions_conferences_nickname'), 'divisions_conferences', ['nickname'], unique=False)
    pass # Made no-op as these columns/indexes are likely created by earlier f626a8bff0f1 and later cda6110c2531
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_divisions_conferences_nickname'), table_name='divisions_conferences')
    # op.drop_column('divisions_conferences', 'nickname')
    # op.drop_index(op.f('ix_leagues_nickname'), table_name='leagues')
    # op.drop_column('leagues', 'nickname')
    pass # Made no-op
    # ### end Alembic commands ### 