"""add_conversation_order_field

Revision ID: b667cd5de716
Revises: add_unique_constraints
Create Date: 2025-03-10 06:25:47.661049+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b667cd5de716'
down_revision: Union[str, None] = 'add_unique_constraints'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('order', sa.Integer(), nullable=True))
    op.drop_index('ix_leagues_name', table_name='leagues')
    op.create_index(op.f('ix_leagues_name'), 'leagues', ['name'], unique=True)
    op.drop_index('ix_stadiums_name', table_name='stadiums')
    op.create_index(op.f('ix_stadiums_name'), 'stadiums', ['name'], unique=True)
    op.drop_index('ix_teams_name', table_name='teams')
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.create_index('ix_teams_name', 'teams', ['name'], unique=False)
    op.drop_index(op.f('ix_stadiums_name'), table_name='stadiums')
    op.create_index('ix_stadiums_name', 'stadiums', ['name'], unique=False)
    op.drop_index(op.f('ix_leagues_name'), table_name='leagues')
    op.create_index('ix_leagues_name', 'leagues', ['name'], unique=False)
    op.drop_column('conversations', 'order')
    # ### end Alembic commands ### 