"""add_sport_to_stadiums

Revision ID: c6bf75f04c69
Revises: da5f17b2e18c
Create Date: 2025-06-02 17:32:53.429905+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql # Not strictly needed for String

# revision identifiers, used by Alembic.
revision: str = 'c6bf75f04c69'
down_revision: Union[str, None] = 'da5f17b2e18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stadiums', sa.Column('sport', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_stadiums_sport'), 'stadiums', ['sport'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stadiums_sport'), table_name='stadiums')
    op.drop_column('stadiums', 'sport')
    # ### end Alembic commands ### 