"""Add sponsor_id to players table

Revision ID: 67062e0a6c20
Revises: a3e3e3e3e3e3
Create Date: 2025-07-19 00:41:39.451471+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67062e0a6c20'
down_revision: Union[str, None] = 'a3e3e3e3e3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporates_country'), table_name='corporate')
    op.drop_index(op.f('ix_corporates_industry'), table_name='corporate')
    op.drop_index(op.f('ix_corporates_name'), table_name='corporate')
    op.drop_index(op.f('ix_corporates_nickname'), table_name='corporate')
    op.create_index('ix_corporate_country', 'corporate', ['country'], unique=False)
    op.create_index(op.f('ix_corporate_industry'), 'corporate', ['industry'], unique=False)
    op.create_index('ix_corporate_name', 'corporate', ['name'], unique=False)
    op.create_index(op.f('ix_corporate_nickname'), 'corporate', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporate_nickname'), table_name='corporate')
    op.drop_index('ix_corporate_name', table_name='corporate')
    op.drop_index(op.f('ix_corporate_industry'), table_name='corporate')
    op.drop_index('ix_corporate_country', table_name='corporate')
    op.create_index(op.f('ix_corporates_nickname'), 'corporate', ['nickname'], unique=False)
    op.create_index(op.f('ix_corporates_name'), 'corporate', ['name'], unique=False)
    op.create_index(op.f('ix_corporates_industry'), 'corporate', ['industry'], unique=False)
    op.create_index(op.f('ix_corporates_country'), 'corporate', ['country'], unique=False)
    # ### end Alembic commands ### 