"""create corporate entity table

Revision ID: 7e5a3f289df7
Revises: 3a7eb620db47
Create Date: 2025-07-11 22:03:21.095654+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e5a3f289df7'
down_revision: Union[str, None] = '3a7eb620db47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('media_department', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corporates_country', 'corporates', ['country'], unique=False)
    op.create_index('ix_corporates_industry', 'corporates', ['industry'], unique=False)
    op.create_index(op.f('ix_corporates_name'), 'corporates', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporates_name'), table_name='corporates')
    op.drop_index('ix_corporates_industry', table_name='corporates')
    op.drop_index('ix_corporates_country', table_name='corporates')
    op.drop_table('corporates')
    # ### end Alembic commands ### 