"""add_sponsor_id_to_players_table_and_other_missing_columns

Revision ID: 39bedf8c62d3
Revises: 
Create Date: 2025-07-19 01:14:39.439794+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39bedf8c62d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporates_country'), table_name='corporate')
    op.drop_index(op.f('ix_corporates_industry'), table_name='corporate')
    op.drop_index(op.f('ix_corporates_name'), table_name='corporate')
    op.drop_index(op.f('ix_corporates_nickname'), table_name='corporate')
    op.create_index('ix_corporate_country', 'corporate', ['country'], unique=False)
    op.create_index(op.f('ix_corporate_industry'), 'corporate', ['industry'], unique=False)
    op.create_index('ix_corporate_name', 'corporate', ['name'], unique=False)
    op.create_index(op.f('ix_corporate_nickname'), 'corporate', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporate_nickname'), table_name='corporate')
    op.drop_index('ix_corporate_name', table_name='corporate')
    op.drop_index(op.f('ix_corporate_industry'), table_name='corporate')
    op.drop_index('ix_corporate_country', table_name='corporate')
    op.create_index(op.f('ix_corporates_nickname'), 'corporate', ['nickname'], unique=False)
    op.create_index(op.f('ix_corporates_name'), 'corporate', ['name'], unique=False)
    op.create_index(op.f('ix_corporates_industry'), 'corporate', ['industry'], unique=False)
    op.create_index(op.f('ix_corporates_country'), 'corporate', ['country'], unique=False)
    # ### end Alembic commands ### 