"""add_division_conference_model

Revision ID: 37bc24210b8f
Revises: b667cd5de716
Create Date: 2025-03-13 00:40:52.161820+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37bc24210b8f'
down_revision: Union[str, None] = 'b667cd5de716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('production_companies')
    # op.drop_table('brand_relationships')
    # op.drop_table('team_ownerships')
    # op.drop_index('ix_teams_name', table_name='teams')
    # op.drop_table('teams')
    # op.drop_index('ix_stadiums_name', table_name='stadiums')
    # op.drop_table('stadiums')
    # op.drop_table('game_broadcasts')
    # op.drop_table('broadcast_companies')
    # op.drop_table('players')
    # op.drop_table('brands')
    # op.drop_table('production_services')
    # op.drop_index('ix_leagues_name', table_name='leagues')
    # op.drop_table('leagues')
    # op.drop_table('team_records')
    # op.drop_table('league_executives')
    # op.drop_table('games')
    # op.drop_table('broadcast_rights')
    pass # Made no-op as these tables are either obsolete or created by f626a8bff0f1
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('broadcast_rights', ... )
    # ... (all the create_table calls from original downgrade) ...
    pass # Made no-op
    # ### end Alembic commands ### 