"""add nickname to entities

Revision ID: 6ca0792d82f5
Revises: 66c77d9feb51
Create Date: 2025-07-10 20:25:31.949775+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca0792d82f5'
down_revision: Union[str, None] = '66c77d9feb51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('nickname', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_brands_nickname'), 'brands', ['nickname'], unique=False)
    op.add_column('broadcast_rights', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('broadcast_rights', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.add_column('game_broadcasts', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('game_broadcasts', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.add_column('league_executives', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_league_executives_nickname'), 'league_executives', ['nickname'], unique=False)
    op.add_column('players', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_players_nickname'), 'players', ['nickname'], unique=False)
    op.add_column('production_services', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('production_services', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.add_column('stadiums', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_stadiums_nickname'), 'stadiums', ['nickname'], unique=False)
    op.add_column('teams', sa.Column('nickname', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_teams_nickname'), 'teams', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_nickname'), table_name='teams')
    op.drop_column('teams', 'nickname')
    op.drop_index(op.f('ix_stadiums_nickname'), table_name='stadiums')
    op.drop_column('stadiums', 'nickname')
    op.drop_column('production_services', 'nickname')
    op.drop_column('production_services', 'name')
    op.drop_index(op.f('ix_players_nickname'), table_name='players')
    op.drop_column('players', 'nickname')
    op.drop_index(op.f('ix_league_executives_nickname'), table_name='league_executives')
    op.drop_column('league_executives', 'nickname')
    op.drop_column('game_broadcasts', 'nickname')
    op.drop_column('game_broadcasts', 'name')
    op.drop_column('broadcast_rights', 'nickname')
    op.drop_column('broadcast_rights', 'name')
    op.drop_index(op.f('ix_brands_nickname'), table_name='brands')
    op.drop_column('brands', 'nickname')
    # ### end Alembic commands ### 